const ActionType = {
  SET_USER: 'SET_USER',
  RESET_USER: 'RESET_USER',
  SET_FORM_SEARCH: 'SET_FORM_SEARCH',
  RESET_FORM_SEARCH: 'RESET_FORM_SEARCH',
  SET_SCHEDULE_SELECTED: 'SET_SCHEDULE_SELECTED',
  RESET_SCHEDULE_SELECTED: 'RESET_SCHEDULE_SELECTED',
  SET_SEAT: 'SET_SEAT',
  RESET_SEAT: 'RESET_SEAT',
  UPDATE_SEAT: 'UPDATE_SEAT',
  SET_FORM_ORDER: 'SET_FORM_ORDER',
  RESET_FORM_ORDER: 'RESET_FORM_ORDER',
}

export default ActionType
